services:
  ex-dock:
    build: .
    ports:
      - "8888:8888"
  database:
    image: postgres:14-alpine
    ports:
      - "5432:8890"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=ex-dock
    volumes:
      - ./database/ex-dock.sql:/docker-entrypoint-initdb.d/datadump.sql
  # This is only used for testing purposes
  testDatabase:
    image: postgres:14-alpine
    ports:
      - "5432:8890"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=ex-dock
    volumes:
      - ./database/ex-dock.sql:/docker-entrypoint-initdb.d/datadump.sql
