services:
  testDatabase:
    image: postgres:14-alpine
    ports:
      - "5432:8890"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=ex-dock
    volumes:
      - ../database/ex-dock.sql:/docker-entrypoint-initdb.d/datadump.sql
