services:
  testDatabase:
    image: postgres:14-alpine
    ports:
      - 8890:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=ex-dock
      - DOCKER_RUNNING=true
    volumes:
      - ../database/ex-dock.sql:/docker-entrypoint-initdb.d/datadump.sql
