name: Run the tests

on:
  pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_class:
          # Codecs
          - "com.ex_dock.ex_dock.codecs.template_engine.SingleUseTemplateDataCodecTest"

          # Templating Engine
          - "com.ex_dock.ex_dock.frontend.template_engine.TemplateEngineVerticleTest"

          # Database
          - "com.ex_dock.ex_dock.database.account.AccountJdbcVerticleTest"
    steps:
      - name: Test file location
        run: |
          ls

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-java@v4.4.0
        with:
          java-version: 21
          distribution: oracle
          cache: maven

      - name: Install dependencies
        run: mvn clean install -DskipTests=true --no-transfer-progress

      - name: Install test dependencies
        run: mvn test -DskipTests=true --no-transfer-progress

      - name: Run Tests
        run: |
          docker compose -f .ci/docker-compose.yaml up
          mvn test -Dtest=${{ matrix.test_class }} --no-transfer-progress
