name: Run the tests

on:
  pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      database:
        image: postgres:14-alpine
        ports:
          - 5432:8890
        env:
          POSTGRES_USER: docker
          POSTGRES_PASSWORD: docker
          POSTGRES_DB: ex-dock
#        volumes:
#          - ${{ github.workspace }}/database/ex-dock.sql:/docker-entrypoint-initdb.d/ex-dock.sql
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 20
    strategy:
      matrix:
        test_class:
          # Codecs
          - "com.ex_dock.ex_dock.codecs.template_engine.SingleUseTemplateDataCodecTest"

          # Templating Engine
          - "com.ex_dock.ex_dock.frontend.template_engine.TemplateEngineVerticleTest"

          # Database
          - "com.ex_dock.ex_dock.database.account.AccountJdbcVerticleTest"
    steps:
      - name: Test file location
        run: ls

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-java@v4.4.0
        with:
          java-version: 21
          distribution: oracle
          cache: maven

      - name: Install dependencies
        run: mvn clean install -DskipTests=true --no-transfer-progress

      - name: Install test dependencies
        run: mvn test -DskipTests=true --no-transfer-progress

      - name: Migrate database
        uses: vovavc/migrate-github-action@v0.2.1
        with:
          path: ./database
          database: postgres://docker:docker@localhost:5432/ex-dock?sslmode=disable
          command: up

      - name: Run Tests
        run: mvn test -Dtest=${{ matrix.test_class }} --no-transfer-progress
